version: '3'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:  S0f773k.001
      MYSQL_DATABASE: testdb
      MYSQL_USER: jagalvanr
      MYSQL_PASSWORD: S0f773k.001
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8080:8080
volumes:
  dbdata:      